extends: reporanger/superpowers

labels:
  greenkeeper: merge
  dependencies: merge
  contributor: 
    action: comment
    delay: 0s
    message: "@all-contributors add @$AUTHOR for code"
  translator: 
    action: comment
    delay: 0s
    message: "@all-contributors add @$AUTHOR for translation"
  duplicate:
    action: close
    delay: 2 days
    comment: ⚠️ This has been marked to be closed in $DELAY.
  'theme/language':
    action: close
    delay: 5 days
    comment: |
      This issue has been marked "$LABEL" and will be closed in $DELAY. As of Carbon `3.0.0`, the Carbon core team is no longer implementing new themes or languages (although the ability to create your own will be implemented soon!). However, PRs to add new ones will be happily accepted.

      Please see https://github.com/carbon-app/carbon/blob/master/.github/CONTRIBUTING.md#adding-themeslanguages for notes on how to do so 👌. 

commits: 
  - action: label
    pattern: 'upgrade dep'
    labels: 
      - maintenance
  
