labels:
  wontfix: true
  invalid: true
  stale: true
  duplicate:
    delayTime: 3 days
    comment: This issue has been marked as a $LABEL. It will be closed in $CLOSE_TIME . . .
  "theme/language":
    delayTime: 5 days
    comment: |
      This issue has been marked "$LABEL" and will be closed in $CLOSE_TIME. As of Carbon `3.0.0`, the Carbon core team is no longer implementing new themes or languages (although the ability to create your own will be implemented soon!). However, PRs to add new ones will be happily accepted.
      
      Please see https://github.com/dawnlabs/carbon/blob/master/.github/CONTRIBUTING.md#a-note-on-adding-themeslanguages for notes on how to do so 👌. 
