language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - node_modules
    - '~/.cache'
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn start & wait-on http://localhost:3000 && CYPRESS_CI=true yarn cy:run --config baseUrl=http://localhost:3000
env:
  global:
    secure: vDOtuvz5TE9CWh5Sotj936YaFQtIF2u8ZKKqokWqozO1RSbZ+FOwE1t31a5MxsKIsH1BSzGDEIkOJ32qFn+M8MWu848sqNzxsfC4gAx+66dE/or0DCv+42gncpqzXSDe8FziOPcW5SutVZhK/4X5T7WIeo7DTld5UuWyWkMztnCPL9WzYfM+jDHpi+F/CyPSqpGGWsXpq57i8IOvSzPosKlk/8pKnm7T5vWlqb4NTvR/nfZuPqfH1fQJbhuZLyXiEpXEGHz3zuSmoKgx7/HZKpaRsRssSrpYTeE63Bw/o+CSV+a81xFXTptu+sa4S1hcHKs3uxwudS/ym4p0cheTkBHzB/Rqljw9Wf2Qq+KL9Z3i+bA0lS+iMZTAABRZ8TGptdlfSRZcjsPEbznRGOPFdyUag+q/xOiAY1+ch/cztI8VR1RGpx3LeUWtn6szkfVEpJeT/sqeTgpp9SvND+O8gUCBnAsndNghedAVl7GHUTkSVlIUPHLD9Esl/V7C/9ItZ9fkQU0msIqx/kxICzwk+QW6q4hLZje9KCt9JqGC09+4GyIbei+jWDwNEbus19OW+D90m4vAub0H7FTQCgH7ZbKysl2yYantAjCxr0m19StGuUbyMIaJaub9ClkHLdk4dxdetY6S0Wlsv8Yw1CVV20NASwYSt0N0x8uPCI0MvsQ=
