language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
after_script:
  - "./node_modules/.bin/now-travis"
env:
  global:
  - secure: n6rdYtl9HwHzfgKcG79UWWL4ncKI0LKpJmEiuWAaS/SmNAUDrMVHLZZ6SMGxVaUi3B66QRmoa0gcm6u+LZeVO3twiHQ57TcjWNiR/Nug9Ff+hnvO1ydoGuPk74OIG8GYUMKLI5JSf0/ANnWPeWvZkPAmUAc1L4kyqbdTxFPx91KLLKR6XJTiMhU6hmfiQSxlaiEnvbXR7zCiiwq43IBulPrjXNfnPKN9tD4SqxwuCP3CGxlPE7RnwQ5S1bnozfKAK+LliLkGor0K9Wh71enTLOzcMenQL+7bqNdo8JwAvPlfaGO+mEIWc/tE1ya3WBVXGqEsFADi10oZG1HH9jMkzi6/y3W/FoK0tZ4JCGz3nRRQiMUai6h7V0DUthd6QKN3TXlC8MXfNGY30ur8guy7u920uKd5F71yTF11QPCwtUJyAKlLnlHF1GZdDbVMyA5fr9dNvS6VA4rwuWRrAjDz923NFBy4bQhPisxF2rOuzqgVvzNpmIlUhyGbeuRtLxIz8Cs/HXuwsiAANYabb7Cxe7He9jx3/DL27LODJkIaYwJKGo9AAfC6cfG60b/fXlZhRzoxTjHkHD9Qf/6X/fhVw43S1ha+kM4YJR88k4A3VFcH7msrHRmvij3LIdjkMmROFzfrSQwGU4RRuQ3qhqr5Kc7t2MVQRYJvA2cQ/qrr4fM=
