name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: npm install, lint, build, and test
        run: |
          yarn
          npm run lint --if-present
          npm run build --if-present
          npm start & npx wait-on http://localhost:3000 && npm run cy:run -- --config baseUrl=http://localhost:3000
          # --record --key 26c0b9eb-40f9-4ca6-b91d-a39f03652011
        env:
          CI: true
          CYPRESS_CI: true
